# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            bin
tagline:          'c# programmer - weeb'
description:      'weeb and C# developer who writes some random development resources and tips'
url:              https://blog.bin.moe
baseurl:          /

author:
  name:           'bin'
  url:            https://twitter.com/binuwu
  github:         https://github.com/binsenpai

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/binsenpai/blog.bin.moe
