# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            bin
tagline:          'c# programmer - weeb'
description:      'weeb and C# developer who writes some random development resources and tips'
meta_desc:        'hi this is my blog, i write random stuff about development, my current projects, anime/weeb, or whatever i''m interested in at the moment. check this place out if you like coding, my projects, anime, or japan.'
url:              https://blog.bin.moe
baseurl:          /

author:
  name:           'bin'
  url:            https://twitter.com/binuwu
  github:         https://github.com/binsenpai

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/binsenpai/blog.bin.moe
