# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            bin
tagline:          'c# programmer - weeb'
description:      'C# programmer and established weeaboo. I''ll write about some of my adventures here and there, and also some neat tips/tricks. Check out my website <a href="https://bin.moe">here.</a>'
url:              https://blog.bin.moe
baseurl:          /

author:
  name:           'bin'
  url:            https://twitter.com/binuwu
  github:         https://github.com/binsenpai

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/binsenpai/blog.bin.moe
